version: '3.9' # version of compose format

services:
  combine-data:
    container_name: combine-data
    build:
      context: ./notebooks/3-combine-data
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8888:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/3-combine-data/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data

  filter-data:
    container_name: filter-data
    build:
      context: ./notebooks/4-filter-data
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8889:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/4-filter-data/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data

  process-data:
    container_name: process-data
    build:
      context: ./notebooks/5-process-data
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8890:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/5-process-data/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data

  split-data:
    container_name: split-data
    build:
      context: ./notebooks/6-split-data
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8891:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/6-split-data/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data

  train:
    container_name: train
    build:
      context: ./notebooks/7-train
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8892:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/7-train/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./model-fine-tuned:/home/jovyan/model-fine-tuned
      - ./data:/home/jovyan/data

  inference:
    container_name: inference
    build:
      context: ./notebooks/8-inference
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8893:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/8-inference/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./model-fine-tuned:/home/jovyan/model-fine-tuned
      - ./data:/home/jovyan/data
