name: train
dependencies:
  - python=3.10
  - pip==22.3
  - pip:
    - nb_black==1.0.7
    - boto3
    - s3fs
    - Jinja2==3.1.2
    - openpyxl==3.0.10
    - pandas==1.5.1
    - matplotlib==3.6.1
    - distributed==2022.10.1
    - dask[dataframe]==2022.10.1
    - dask[distributed]==2022.10.1
    - scikit-learn==1.1.3
    - IProgress==0.4
    - ipywidgets==8.0.2
    - datasets==2.6.1
    - torch==1.13.0
  - conda==4.3.16
  - conda:
    - ipykernel==6.16.2
    - pyarrow==9.0.0
    - fastparquet==0.8.3
    - transformers==4.23.1
